### ISSUE TITLE
As a developer, i need to install all needed dependencies, so i can get an overview on what to read and learn.

### ISSUE THREAD

**Issue by atorczynski** [atorczynski/ecommercio#4]
- [x] create-react-app #21 
- [x] react-router-dom (Routing the app.) G. dep.
- [x] prop-types (Checking for prop types) G. dep. #30 
- [x] Axios #50
- [x] Cheerio #50
- [x] Eslint (consistant code) - Dev dep. #23 
- [x] Prettier (consistant formating) Dev dep. #23 
- [x] Mongodb (Database storage) G. dep.
- [x] Emotion.sh (For styling components) G. dep. #27 
- [x] Storybooks (https://storybook.js.org/) Dev. dep.
- [x] dotenv (Hiding private variables) Dev. dep.
- [x] passport.js (Creating a JWT login) G. dep. #50
- [x] Expressjs (Building API) - G. dep.
